# Generated by Django 6.0.3 on 2026-04-28 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0002_alter_profession_category_alter_profession_name_and_more'),
        ('resumes', '0002_resume_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='profession',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='resumes', to='professions.profession'),
            preserve_default=False,
        ),
    ]
