from django.urls import path
from . import views
from django.views.generic import TemplateView


urlpatterns = [
    #path('manufacturers/<int:manufacturer_id>/products/', views.ManufacturerProductsView.as_view(), name='manufacturer_products'),
    path('<str:sku>/availability/', views.UpdateProductAvailabilityView.as_view(), name='update_product'),
    path('about-us/', views.AboutUsView.as_view(), name='about_html'),
    path('', views.WelcomeHomeView.as_view(), name='welcome_home'),
    path('faq/', views.FAQView.as_view(), name='faq'),
    path('product/<str:product_sku>/detail/', views.ProductDetailWithRelatedView.as_view(), name='product_detail'),
    path('manufacturers/', views.ManufacturerListView.as_view(), name='manufacturers_list'),
    path('old-home/', views.RedirectToHomeView.as_view(), name='old_home'),
    path('old-products-url/<str:old_sku>/', views.OldProductURLRedirectView.as_view(), name='redirect'),
    #path('products/search/', views.ProductSearchView.as_view(), name='product_search'),
    path('legacy-search/', views.LegacySearchRedirectView.as_view(), name='search_redirect'),
    path('find-manufacturer/', views.ManufacturerLookupRedirectView.as_view(), name='find_manufacturer'),
    path('product-status/<str:product_sku>/', views.ProductAvailabilityRedirectView.as_view(), name='product_status'),
    path('product-unavailable/', views.ProductUnavailableView.as_view(), name='product_unavailable'),
    path('manufacturers/<int:pk>/', views.ManufacturerDetailView.as_view(), name='manufacturer_detail'),
    path('manufacturers/<int:pk>/products/', views.ManufacturerProductsDetailView.as_view(), name='manufacturers_all_products'),
    path('products/counted/<str:product_sku>/', views.ProductDetailWithViewCount.as_view(), name='views_count'),
    path('products/similar/<str:product_sku>/', views.ProductDetailWithSimilarPriceView.as_view(), name='similar_products'),
    path('products/filtered/', views.ProductFilteredListView.as_view(), name='products_filtered'),
    path('products/sortable/', views.ProductSortableListView.as_view(), name='products_sortable'),
    path('products/advanced-filter/', views.ProductAdvancedFilterListView.as_view(), name='products_advanced_filter'),
    path('products/search', views.ProductSearchView.as_view(), name='products_search'),
    path('products/<str:product_sku>/', views.ProductDetailBySkuView.as_view(), name='product_detail_by_sku'),
    path('manufacturers/stats/', views.ManufacturerStatsListView.as_view(), name='manufacturers_stats'),
    path('contact/', views.ContactFormView.as_view(), name='contact'),
    path('contact/success/', views.TemplateView.as_view(template_name='webshop/contact_success.html'), name='contact_success'),
    path('feedback/', views.FeedbackFormView.as_view(), name='feedback_page'),
    path('feedback/thank-you/', views.FeedbackThankYouView.as_view(), name='feedback_thank_you'),
    path('newsletter/signup/', views.NewsletterSignupView.as_view(), name='newsletter_signup_page'),
    path('newsletter/success/', views.TemplateView.as_view(template_name='webshop/newsletter_success.html'), name='newsletter_success'),
    path('shipping-calculator/', views.ShippingCalculatorView.as_view(), name='shipping_calculator_page'),
    path('ask/', views.AskQuestionView.as_view(), name='ask_question_page'),
    path('ask/sent/', views.QuestionSentView.as_view(), name='ask_sent_page'),
    path('area/calculate/', views.RectangleAreaView.as_view(), name='calculate_area_page'),
    path('area/result/', views.RectangleAreaResultView.as_view(), name='area_result'),
    path('register/', views.UserRegistrationView.as_view(), name='register_user_page'),
    path('register/success/', views.RegistrationSuccessView.as_view(), name='register_success_page'),
    path('order/custom/', views.CustomProductOrderView.as_view(), name='custom_order_page'),
    path('order/confirm/', views.OrderConfirmationView.as_view(), name='order_confirmation_page'),
]
