# Generated by Django 6.0.3 on 2026-04-27 22:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название вакансии')),
                ('description', models.TextField(verbose_name='Общее описание')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Зарплата')),
                ('experience', models.CharField(blank=True, max_length=255, null=True, verbose_name='Опыт работы')),
                ('employment_type', models.CharField(choices=[('full_time', 'Полная'), ('part_time', 'Частичная'), ('internship', 'Стажировка'), ('contract', 'Контракт'), ('remote', 'Удалённая работа')], default='full_time', max_length=255, verbose_name='Тип занятости')),
                ('schedule', models.CharField(choices=[('day', 'Дневные смены'), ('night', 'Ночные смены'), ('flexible', 'Гибкий график'), ('shift', 'Сменный график'), ('remote', 'Удалённо')], default='day', max_length=255, verbose_name='График работы')),
                ('working_hours', models.CharField(blank=True, max_length=255, null=True, verbose_name='Рабочие часы')),
                ('responsibilities', models.TextField(blank=True, null=True, verbose_name='Обязанности')),
                ('conditions', models.TextField(blank=True, null=True, verbose_name='Условия работы')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy', to='companies.company')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-created_at'],
            },
        ),
    ]
