# Generated by Django 6.0.3 on 2026-04-28 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_vacancy_company'),
        ('professions', '0002_alter_profession_category_alter_profession_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='profession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='professions.profession'),
        ),
    ]
