# Generated by Django 6.0.3 on 2026-04-28 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_vacancy_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='experience_required',
            field=models.CharField(choices=[('with_experience', 'С опытом'), ('without_experience', 'Без опыта')], default='with_experience', max_length=50, verbose_name='Требуемый опыт'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_type',
            field=models.CharField(choices=[('weekly', 'Раз в неделю'), ('monthly', 'Раз в месяц'), ('twice_monthly', '2 раза в месяц'), ('daily', 'Ежедневно'), ('hourly', 'По часам'), ('negotiable', 'Договорная')], default='negotiable', max_length=255, verbose_name='Тип зарплаты'),
            preserve_default=False,
        ),
    ]
