# Generated by Django 6.0.3 on 2026-03-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'color')},
        ),
        migrations.AddField(
            model_name='product',
            name='bridge_mm',
            field=models.PositiveIntegerField(blank=True, help_text='Bridge: 14 mm', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fit_low_high',
            field=models.PositiveIntegerField(default=50, help_text='Fit Low (0) to High (100)'),
        ),
        migrations.AddField(
            model_name='product',
            name='fit_narrow_wide',
            field=models.PositiveIntegerField(default=50, help_text='Fit Narrow (0) to Wide (100)'),
        ),
        migrations.AddField(
            model_name='product',
            name='frame_front_mm',
            field=models.PositiveIntegerField(blank=True, help_text='Frame front: 155 mm', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='lens_height_mm',
            field=models.PositiveIntegerField(blank=True, help_text='Lens height: 30 mm', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='lens_width_mm',
            field=models.PositiveIntegerField(blank=True, help_text='Lens width: 59 mm', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='temple_length_mm',
            field=models.PositiveIntegerField(blank=True, help_text='Temple length: 111 mm', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Example: Wraparound Sunglasses in Blue Nylon'),
        ),
        migrations.AlterField(
            model_name='product',
            name='details',
            field=models.JSONField(default=list, help_text='List of details, e.g. ["Blue Nylon Frame", "Blue Mirror Lenses"]'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.CharField(help_text='e.g. Blue / Blue', max_length=50),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color_hex',
            field=models.CharField(default='#000000', help_text='e.g. #111111', max_length=7),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='size',
        ),
    ]
