# Generated by Django 6.0.3 on 2026-04-28 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profession',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='professions', to='professions.categoryprofession'),
        ),
        migrations.AlterField(
            model_name='profession',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название профессии'),
        ),
        migrations.AlterUniqueTogether(
            name='profession',
            unique_together={('category', 'name')},
        ),
    ]
