# Generated by Django 6.0.3 on 2026-04-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='name',
        ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
