# Generated by Django 6.0.3 on 2026-04-16 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_gallery_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='title',
        ),
    ]
